#!/bin/bash

# Set decoration geometry
berryc border_width       2
berryc inner_border_width 3
berryc title_height       20
berryc top_gap            10
berryc edge_gap           10 10 55 10

# Set decoration colors
berryc focus_color         1B1924
berryc unfocus_color       09080C
berryc inner_focus_color   D7757D
berryc inner_unfocus_color D1616A
berryc text_focus_color    2B2839
berryc text_unfocus_color  09080C

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc decorate_new "true"
berryc set_font    "Scientifica-8"
